substitutions:
  _REGION: us-central1
  _ARTIFACT_REGISTRY_REPO: conversationalengine-repo

steps:
  # Build the core service image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-core-service'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/noyco-473111/${_ARTIFACT_REGISTRY_REPO}/core-service:$COMMIT_SHA'
      - '-f'
      - 'core/Dockerfile'
      - '.'
  
  # Push the core service image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-core-service'
    waitFor: ['build-core-service']
    args: ['push', '${_REGION}-docker.pkg.dev/noyco-473111/${_ARTIFACT_REGISTRY_REPO}/core-service:$COMMIT_SHA']

  # Deploy core service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-core-service'
    waitFor: ['push-core-service']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'conversationalengine-core'
      - '--image'
      - '${_REGION}-docker.pkg.dev/noyco-473111/${_ARTIFACT_REGISTRY_REPO}/core-service:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--concurrency'
      - '50'
      - '--update-secrets'
      - conversationalengine-secrets=conversationalengine-secrets:latest
      
images:
  - '${_REGION}-docker.pkg.dev/noyco-473111/${_ARTIFACT_REGISTRY_REPO}/core-service:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: projects/562270549707/secrets/conversationalengine-secrets/versions/latest
      env: 'conversationalengine-secrets'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'