substitutions:
  _REGION: us-central1
  _ARTIFACT_REGISTRY_REPO: conversationalengine-repo

steps:
  # Build the memory service image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-memory'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/noyco-473111/${_ARTIFACT_REGISTRY_REPO}/memory-service:$COMMIT_SHA'
      - '-f'
      - 'memory/Dockerfile'
      - '.'
  
  # Push the memory service image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-memory'
    waitFor: ['build-memory']
    args: ['push', '${_REGION}-docker.pkg.dev/noyco-473111/${_ARTIFACT_REGISTRY_REPO}/memory-service:$COMMIT_SHA']

  # Deploy memory service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-memory'
    waitFor: ['push-memory']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'conversationalengine-memory'
      - '--image'
      - '${_REGION}-docker.pkg.dev/noyco-473111/${_ARTIFACT_REGISTRY_REPO}/memory-service:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1' # Required for in-memory cache
      - '--max-instances'
      - '3'
      - '--concurrency'
      - '80'
      - '--update-secrets'
      - conversationalengine-secrets=conversationalengine-secrets:latest 

images:
  - '${_REGION}-docker.pkg.dev/noyco-473111/${_ARTIFACT_REGISTRY_REPO}/memory-service:$COMMIT_SHA'

# availableSecrets:
#   secretManager:
#     - versionName: projects/562270549707/secrets/conversationalengine-secrets/versions/latest
#       env: 'conversationalengine-secrets'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'